theme: jekyll-theme-minimal
title: Rhoda Esquivel
description: Software engineer, entrepreneur, best-selling book co-author
logo: https://media-exp1.licdn.com/dms/image/C5603AQG891Lx1swHDA/profile-displayphoto-shrink_800_800/0/1622874348909?e=1642032000&v=beta&t=T-UnL_hRFZ01-kC7w83HWoWnNeHEz3Rhf_GAb-Xx1YQ
show_downloads: false
