theme: jekyll-theme-minimal
title: Rhoda Esquivel
description: Software engineer, entrepreneur, best-selling book co-author
logo: https://media-exp1.licdn.com/dms/image/C5603AQG891Lx1swHDA/profile-displayphoto-shrink_800_800/0/1622874348909?e=1672876800&v=beta&t=JDdlbuC8S3nqybkTlE-6fueFljTgTEaXr5V_V4Moc-k 
show_downloads: false
