theme: jekyll-theme-minimal
title: Rhoda Esquivel
description: Software engineer, entrepreneur, best-selling book co-author
logo: https://lh3.googleusercontent.com/8NYw6Gap-_7ldQbDyuFGOX9ha5OLHnmnwzrL7yAn6bqx-EhRaPVLp4HjmD-dkerVPo8Y-71pxgo6GdM_Z6xhub4R6zgWzbqRzaN1jV-zCO-drvc7v55D0VuqjAHLvWuLcJXvRRUzvwA=w2400
show_downloads: false
